name: Go

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: lint & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.3

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Install buf
        run: go install github.com/bufbuild/buf/cmd/buf@latest

      - uses: actions/checkout@v3

      - name: Run lint
        run: task lint

      - name: Run test
        run: task test
